name: upload

on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    container: chef/chefworkstation:latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: |
          mkdir ~/.chef
          echo "current_dir = File.dirname(__FILE__)\nlog_level :info\nlog_location STDOUT\nnode_name \"${{ secrets.CHEF_USER }}\"\nclient_key \"#{current_dir}/user.pem\"\nchef_server_url \"${{ secrets.CHEF_URL }}\"\ncookbook_path [\"#{current_dir}/../cookbooks\"]" > ~/.chef/knife.rb
          echo "${{ secrets.CHEF_PEM }}" > ~/.chef/user.pem
          berks install
          berks upload
